DROP DATABASE QL_Giay

CREATE DATABASE QL_Giay
GO
USE QL_Giay
GO

CREATE TABLE TAIKHOAN (
    MATK INT IDENTITY(1,1) PRIMARY KEY,
    EMAIL NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU NVARCHAR(100) NOT NULL,
    LOAITK NVARCHAR(10) CHECK (LOAITK IN ('USER', 'ADMIN')) NOT NULL,
    TRANGTHAI BIT DEFAULT 1
)
GO

CREATE TABLE KHACHHANG (
    MAKH INT IDENTITY(1,1) PRIMARY KEY,
    TENKH NVARCHAR(100) NOT NULL,
    MATK INT NOT NULL,
    SDT VARCHAR(15),
    DIACHI NVARCHAR(255),
    FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
)
GO

CREATE TABLE DANHMUC (
    MADM INT IDENTITY(1,1) PRIMARY KEY,
    TENDM NVARCHAR(100) NOT NULL,
    MOTA NVARCHAR(255)
)
GO

CREATE TABLE MAU (
    MAMAU INT IDENTITY(1,1) PRIMARY KEY,
    TENMAU NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE SIZE (
    MASIZE INT IDENTITY(1,1) PRIMARY KEY,
    TENSIZE NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE THUONGHIEU (
    MATH INT IDENTITY(1,1) PRIMARY KEY,
    TENTH NVARCHAR(100) NOT NULL,
    MOTA NVARCHAR(255),
    LOGO NVARCHAR(255)
)
GO

CREATE TABLE SANPHAM (
    MASP INT IDENTITY(1,1) PRIMARY KEY,
    MADM INT NOT NULL,
    MATH INT NOT NULL,
    TENSP NVARCHAR(100) NOT NULL,
    GIA DECIMAL(18,2) NOT NULL CHECK (GIA >= 0),
    MOTA NVARCHAR(MAX),
    HINHDAIDIEN NVARCHAR(255),
    TRANGTHAI NVARCHAR(10) CHECK (TRANGTHAI IN (N'CÒN', N'HẾT HÀNG')) NOT NULL,
    FOREIGN KEY (MADM) REFERENCES DANHMUC(MADM),
    FOREIGN KEY (MATH) REFERENCES THUONGHIEU(MATH)
)
GO

CREATE TABLE CHITIET_SANPHAM (
    MACTSP INT IDENTITY(1,1) PRIMARY KEY,
    MASP INT NOT NULL,
    MAMAU INT NOT NULL,
    MASIZE INT NOT NULL,
    SLTON INT DEFAULT 0 CHECK (SLTON >= 0),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP) ON DELETE CASCADE,
    FOREIGN KEY (MAMAU) REFERENCES MAU(MAMAU),
    FOREIGN KEY (MASIZE) REFERENCES SIZE(MASIZE)
)
GO

CREATE TABLE CHITIET_GIOHANG (
    MAKH INT NOT NULL,
    MACTSP INT NOT NULL,
    SL INT CHECK (SL > 0),
    PRIMARY KEY (MAKH, MACTSP),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MACTSP) REFERENCES CHITIET_SANPHAM(MACTSP) ON DELETE CASCADE
)
GO

ALTER TABLE CHITIET_GIOHANG ADD DONGIA DECIMAL(18,2) NOT NULL;
--ALTER TABLE CHITIET_GIOHANG ADD CONSTRAINT CK_GIOHANG CHECK ((MAKH IS NOT NULL) OR (SESSIONID IS NOT NULL))
GO

CREATE TABLE PHUONGTHUCTHANHTOAN (
    MAPTTT INT IDENTITY(1,1) PRIMARY KEY,
    TENPHUONGTHUC NVARCHAR(50) CHECK (TENPHUONGTHUC IN (N'COD', N'VNPAY')) NOT NULL
)
GO

CREATE TABLE VOUCHER (
    MAVOUCHER INT IDENTITY(1,1) PRIMARY KEY,
    TENVOUCHER NVARCHAR(100),
    MAGIAMGIA NVARCHAR(50),
    GIATRI DECIMAL(5,2) CHECK (GIATRI BETWEEN 0 AND 100), -- phần trăm giảm (%)
    NGAYBD DATE,
    NGAYKT DATE,
    TRANGTHAI NVARCHAR(10) CHECK (TRANGTHAI IN (N'CÒN', N'HẾT HẠN')) NOT NULL
)
GO

CREATE TABLE DONHANG (
    MADH INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT NOT NULL,
    MAPTTT INT NOT NULL,
    MAVOUCHER INT NULL,
    NGAYDAT DATETIME DEFAULT GETDATE(),
    TONGTIEN DECIMAL(18,2) CHECK (TONGTIEN >= 0),
    TRANGTHAI NVARCHAR(20) CHECK (TRANGTHAI IN (N'CHỜ XÁC NHẬN', N'ĐANG GIAO', N'ĐÃ NHẬN', N'HỦY')) NOT NULL,
    DIACHIGIAO NVARCHAR(255),
    SDTGIAO VARCHAR(15),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MAPTTT) REFERENCES PHUONGTHUCTHANHTOAN(MAPTTT),
    FOREIGN KEY (MAVOUCHER) REFERENCES VOUCHER(MAVOUCHER)
)
GO

ALTER TABLE DONHANG ADD PHISHIP DECIMAL(18,2) DEFAULT 0 CHECK (PHISHIP >= 0), TONGTIENCUOI DECIMAL(18,2)
ALTER TABLE DONHANG ADD LYDOHUY NVARCHAR(255) NULL
GO

CREATE TABLE CHITIET_DONHANG (
    MADH INT NOT NULL,
    MACTSP INT NOT NULL,
    SL INT CHECK (SL > 0),
    DONGIA DECIMAL(18,2) CHECK (DONGIA >= 0),
    PRIMARY KEY (MADH, MACTSP),
    FOREIGN KEY (MADH) REFERENCES DONHANG(MADH),
    FOREIGN KEY (MACTSP) REFERENCES CHITIET_SANPHAM(MACTSP)
)
GO

ALTER TABLE CHITIET_DONHANG ADD THANHTIEN AS (SL * DONGIA) PERSISTED
GO

INSERT INTO TAIKHOAN VALUES
('admin@gmail.com','admin','ADMIN',1),
('user1@gmail.com','123456','USER',1),
('user2@gmail.com','123456','USER',1)
GO

INSERT INTO KHACHHANG VALUES
(N'Admin',1,'0900000000',N'TP HCM'),
(N'Nguyễn Văn A',2,'0911111111',N'Đà Nẵng'),
(N'Trần Thị B',3,'0922222222',N'Hà Nội')
GO

INSERT INTO DANHMUC VALUES
(N'Giày Thể Thao',N'Dành cho vận động'),
(N'Giày Da',N'Công sở')
GO

INSERT INTO THUONGHIEU VALUES
(N'Nike',N'Mỹ','nike.png'),
(N'Adidas',N'Đức','adidas.png')
GO

INSERT INTO MAU VALUES (N'Đen'),(N'Trắng')
GO

INSERT INTO SIZE VALUES (N'41'),(N'42')
GO

INSERT INTO SANPHAM VALUES
(1,1,N'Air Jordan',2500000,N'Hot','aj.png',N'CÒN')
GO

INSERT INTO CHITIET_SANPHAM VALUES
(1,1,1,10),
(1,2,2,5)
GO

INSERT INTO CHITIET_GIOHANG VALUES
(2,1,1,2500000)
GO

INSERT INTO PHUONGTHUCTHANHTOAN VALUES (N'COD'),(N'VNPAY')
GO

INSERT INTO DONHANG (MAKH, MAPTTT, MAVOUCHER, TONGTIEN, TRANGTHAI, DIACHIGIAO, SDTGIAO, PHISHIP, TONGTIENCUOI)
VALUES (2, 1, NULL, 2500000, N'CHỜ XÁC NHẬN', N'Đà Nẵng', '0911111111', 30000, 2530000)
GO

INSERT INTO CHITIET_DONHANG VALUES
(1, 1, 1, 2500000)
GO

INSERT INTO VOUCHER (TENVOUCHER, MAGIAMGIA, GIATRI, NGAYBD, NGAYKT, TRANGTHAI)
VALUES
(N'Giảm 10% cho đơn từ 200k', 'SALE10', 10.00, '2025-10-01', '2025-12-31', N'CÒN'),
(N'Khuyến mãi 20% cuối tuần', 'WEEKEND20', 20.00, '2025-11-01', '2025-11-30', N'CÒN'),
(N'Voucher Black Friday 50%', 'BLACK50', 50.00, '2025-11-20', '2025-11-28', N'CÒN'),
(N'Giảm 5% khách hàng mới', 'NEW5', 5.00, '2025-01-01', '2025-12-31', N'CÒN'),
(N'Giảm 15% cho đơn từ 500k', 'VIP15', 15.00, '2025-09-01', '2025-09-30', N'HẾT HẠN');
GO


SELECT * FROM TAIKHOAN
SELECT * FROM KHACHHANG
SELECT * FROM DANHMUC
SELECT * FROM MAU
SELECT * FROM SIZE
SELECT * FROM THUONGHIEU
SELECT * FROM SANPHAM
SELECT * FROM CHITIET_SANPHAM
SELECT * FROM CHITIET_GIOHANG
SELECT * FROM PHUONGTHUCTHANHTOAN
SELECT * FROM VOUCHER
SELECT * FROM DONHANG
SELECT * FROM CHITIET_DONHANG
