// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBanGiay.Models;

#nullable disable

namespace QuanLyBanGiay.Migrations
{
    [DbContext(typeof(QL_GiayContext))]
    [Migration("20251210033550_UpdateVoucherGiatriSize")]
    partial class UpdateVoucherGiatriSize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyBanGiay.Models.ChitietDonhang", b =>
                {
                    b.Property<int>("Madh")
                        .HasColumnType("int")
                        .HasColumnName("MADH");

                    b.Property<int>("Mactsp")
                        .HasColumnType("int")
                        .HasColumnName("MACTSP");

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DONGIA");

                    b.Property<int?>("Sl")
                        .HasColumnType("int")
                        .HasColumnName("SL");

                    b.Property<decimal?>("Thanhtien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29,2)")
                        .HasColumnName("THANHTIEN")
                        .HasComputedColumnSql("([SL]*[DONGIA])", true);

                    b.HasKey("Madh", "Mactsp")
                        .HasName("PK__CHITIET___2F6F1C688CD988B2");

                    b.HasIndex("Mactsp");

                    b.ToTable("CHITIET_DONHANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.ChitietSanpham", b =>
                {
                    b.Property<int>("Mactsp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACTSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mactsp"), 1L, 1);

                    b.Property<int>("Mamau")
                        .HasColumnType("int")
                        .HasColumnName("MAMAU");

                    b.Property<int>("Masize")
                        .HasColumnType("int")
                        .HasColumnName("MASIZE");

                    b.Property<int>("Masp")
                        .HasColumnType("int")
                        .HasColumnName("MASP");

                    b.Property<int?>("Slton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SLTON")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("Mactsp")
                        .HasName("PK__CHITIET___F501C2F57E7AE6CC");

                    b.HasIndex("Mamau");

                    b.HasIndex("Masize");

                    b.HasIndex("Masp");

                    b.ToTable("CHITIET_SANPHAM", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Danhgia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"), 1L, 1);

                    b.Property<bool>("CoTheDanhGia")
                        .HasColumnType("bit");

                    b.Property<int>("MaKh")
                        .HasColumnType("int");

                    b.Property<int>("MaSp")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sao")
                        .HasColumnType("int");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaSp");

                    b.ToTable("Danhgias");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Danhmuc", b =>
                {
                    b.Property<int>("Madm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madm"), 1L, 1);

                    b.Property<string>("Mota")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tendm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENDM");

                    b.HasKey("Madm")
                        .HasName("PK__DANHMUC__603F005C468FB43D");

                    b.ToTable("DANHMUC", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Donhang", b =>
                {
                    b.Property<int>("Madh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madh"), 1L, 1);

                    b.Property<bool>("DaNopTienCOD")
                        .HasColumnType("bit");

                    b.Property<string>("Diachigiao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHIGIAO");

                    b.Property<string>("Lydohuy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LYDOHUY");

                    b.Property<int?>("MaNvg")
                        .HasColumnType("int");

                    b.Property<int?>("Makh")
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    b.Property<int>("Mapttt")
                        .HasColumnType("int")
                        .HasColumnName("MAPTTT");

                    b.Property<int?>("Mavoucher")
                        .HasColumnType("int")
                        .HasColumnName("MAVOUCHER");

                    b.Property<DateTime?>("Ngaydat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYDAT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Phiship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PHISHIP")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Sdtgiao")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDTGIAO");

                    b.Property<decimal?>("Tongtien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONGTIEN");

                    b.Property<decimal?>("Tongtiencuoi")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TONGTIENCUOI");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Madh")
                        .HasName("PK__DONHANG__603F004776DE4EE0");

                    b.HasIndex("MaNvg");

                    b.HasIndex("Makh");

                    b.HasIndex("Mapttt");

                    b.HasIndex("Mavoucher");

                    b.ToTable("DONHANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Khachhang", b =>
                {
                    b.Property<int>("Makh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makh"), 1L, 1);

                    b.Property<bool?>("DaXacNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Loaitk")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("LOAITK");

                    b.Property<string>("MaXacNhan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MATKHAU");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tenkh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENKH");

                    b.Property<DateTime?>("ThoiGianTaoOtp")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianTaoOTP");

                    b.Property<bool?>("Trangthai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Makh")
                        .HasName("PK__KHACHHAN__603F592CE7DCE3EC");

                    b.HasIndex(new[] { "Email" }, "UQ__KHACHHAN__161CF724C8915B15")
                        .IsUnique();

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Mau", b =>
                {
                    b.Property<int>("Mamau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAMAU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mamau"), 1L, 1);

                    b.Property<string>("Tenmau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENMAU");

                    b.HasKey("Mamau")
                        .HasName("PK__MAU__7B7346CF1DCCFB99");

                    b.ToTable("MAU", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Phuongthucthanhtoan", b =>
                {
                    b.Property<int>("Mapttt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPTTT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapttt"), 1L, 1);

                    b.Property<string>("Tenphuongthuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENPHUONGTHUC");

                    b.HasKey("Mapttt")
                        .HasName("PK__PHUONGTH__4F6B743E047617E3");

                    b.ToTable("PHUONGTHUCTHANHTOAN", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Sanpham", b =>
                {
                    b.Property<int>("Masp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masp"), 1L, 1);

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GIA");

                    b.Property<string>("Hinhdaidien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HINHDAIDIEN");

                    b.Property<int>("Madm")
                        .HasColumnType("int")
                        .HasColumnName("MADM");

                    b.Property<int>("Math")
                        .HasColumnType("int")
                        .HasColumnName("MATH");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tensp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENSP");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Masp")
                        .HasName("PK__SANPHAM__60228A3203A8CDD7");

                    b.HasIndex("Madm");

                    b.HasIndex("Math");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Size", b =>
                {
                    b.Property<int>("Masize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASIZE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masize"), 1L, 1);

                    b.Property<string>("Tensize")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENSIZE");

                    b.HasKey("Masize")
                        .HasName("PK__SIZE__3DD4402B8C8AB7DF");

                    b.ToTable("SIZE", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Thuonghieu", b =>
                {
                    b.Property<int>("Math")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Math"), 1L, 1);

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOGO");

                    b.Property<string>("Mota")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENTH");

                    b.HasKey("Math")
                        .HasName("PK__THUONGHI__6023721B5000B73E");

                    b.ToTable("THUONGHIEU", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Voucher", b =>
                {
                    b.Property<int>("Mavoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAVOUCHER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mavoucher"), 1L, 1);

                    b.Property<int>("DaSuDung")
                        .HasColumnType("int");

                    b.Property<string>("GiaTriPhamVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Giatri")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GIATRI");

                    b.Property<bool>("GioiHanMoiKhach")
                        .HasColumnType("bit");

                    b.Property<int?>("GioiHanSuDung")
                        .HasColumnType("int");

                    b.Property<int>("LoaiKhuyenMai")
                        .HasColumnType("int");

                    b.Property<string>("Magiamgia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MAGIAMGIA");

                    b.Property<DateTime?>("Ngaybd")
                        .HasColumnType("date")
                        .HasColumnName("NGAYBD");

                    b.Property<DateTime?>("Ngaykt")
                        .HasColumnType("date")
                        .HasColumnName("NGAYKT");

                    b.Property<int>("NhomKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("PhamViApDung")
                        .HasColumnType("int");

                    b.Property<string>("Tenvoucher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENVOUCHER");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mavoucher")
                        .HasName("PK__VOUCHER__56FC9ADEC3E8C892");

                    b.ToTable("VOUCHER", (string)null);
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.ChitietDonhang", b =>
                {
                    b.HasOne("QuanLyBanGiay.Models.ChitietSanpham", "MactspNavigation")
                        .WithMany("ChitietDonhangs")
                        .HasForeignKey("Mactsp")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIET_D__MACTS__6B24EA82");

                    b.HasOne("QuanLyBanGiay.Models.Donhang", "MadhNavigation")
                        .WithMany("ChitietDonhangs")
                        .HasForeignKey("Madh")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIET_DO__MADH__6A30C649");

                    b.Navigation("MactspNavigation");

                    b.Navigation("MadhNavigation");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.ChitietSanpham", b =>
                {
                    b.HasOne("QuanLyBanGiay.Models.Mau", "MamauNavigation")
                        .WithMany("ChitietSanphams")
                        .HasForeignKey("Mamau")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIET_S__MAMAU__4F7CD00D");

                    b.HasOne("QuanLyBanGiay.Models.Size", "MasizeNavigation")
                        .WithMany("ChitietSanphams")
                        .HasForeignKey("Masize")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIET_S__MASIZ__5070F446");

                    b.HasOne("QuanLyBanGiay.Models.Sanpham", "MaspNavigation")
                        .WithMany("ChitietSanphams")
                        .HasForeignKey("Masp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CHITIET_SA__MASP__4E88ABD4");

                    b.Navigation("MamauNavigation");

                    b.Navigation("MasizeNavigation");

                    b.Navigation("MaspNavigation");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Danhgia", b =>
                {
                    b.HasOne("QuanLyBanGiay.Models.Khachhang", "Khachhang")
                        .WithMany()
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanGiay.Models.Sanpham", "Sanpham")
                        .WithMany()
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khachhang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Donhang", b =>
                {
                    b.HasOne("QuanLyBanGiay.Models.Khachhang", "MaNvgNavigation")
                        .WithMany("DonhangMaNvgNavigations")
                        .HasForeignKey("MaNvg")
                        .HasConstraintName("FK_Donhang_NVG");

                    b.HasOne("QuanLyBanGiay.Models.Khachhang", "MakhNavigation")
                        .WithMany("DonhangMakhNavigations")
                        .HasForeignKey("Makh")
                        .HasConstraintName("FK_DONHANG_KH");

                    b.HasOne("QuanLyBanGiay.Models.Phuongthucthanhtoan", "MaptttNavigation")
                        .WithMany("Donhangs")
                        .HasForeignKey("Mapttt")
                        .IsRequired()
                        .HasConstraintName("FK__DONHANG__MAPTTT__628FA481");

                    b.HasOne("QuanLyBanGiay.Models.Voucher", "MavoucherNavigation")
                        .WithMany("Donhangs")
                        .HasForeignKey("Mavoucher")
                        .HasConstraintName("FK__DONHANG__MAVOUCH__6383C8BA");

                    b.Navigation("MaNvgNavigation");

                    b.Navigation("MakhNavigation");

                    b.Navigation("MaptttNavigation");

                    b.Navigation("MavoucherNavigation");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Sanpham", b =>
                {
                    b.HasOne("QuanLyBanGiay.Models.Danhmuc", "MadmNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Madm")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__MADM__48CFD27E");

                    b.HasOne("QuanLyBanGiay.Models.Thuonghieu", "MathNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("Math")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__MATH__49C3F6B7");

                    b.Navigation("MadmNavigation");

                    b.Navigation("MathNavigation");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.ChitietSanpham", b =>
                {
                    b.Navigation("ChitietDonhangs");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Danhmuc", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Donhang", b =>
                {
                    b.Navigation("ChitietDonhangs");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Khachhang", b =>
                {
                    b.Navigation("DonhangMaNvgNavigations");

                    b.Navigation("DonhangMakhNavigations");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Mau", b =>
                {
                    b.Navigation("ChitietSanphams");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Phuongthucthanhtoan", b =>
                {
                    b.Navigation("Donhangs");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Sanpham", b =>
                {
                    b.Navigation("ChitietSanphams");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Size", b =>
                {
                    b.Navigation("ChitietSanphams");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Thuonghieu", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("QuanLyBanGiay.Models.Voucher", b =>
                {
                    b.Navigation("Donhangs");
                });
#pragma warning restore 612, 618
        }
    }
}
